name: Build Windows App with ToDesktop

on:
  push:
    branches:
      - main  # Runs the build when pushing to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ToDesktop CLI
        run: npm install -g @todesktop/cli

      - name: Authenticate with ToDesktop
        run: todesktop login --token=${{ secrets.TODESKTOP_API_KEY }}

      - name: Build Windows App
        run: todesktop build

      - name: Upload EXE to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: TODOAPP2-Windows
          path: build/  # Adjust if needed based on ToDesktop output
